### ISSUE TITLE
New versions of snowflake don't start properly

### ISSUE THREAD

**Issue by lunarthegrey** [nvjacobo/snowflake#22]
Tested with v2.6.0, it produces the following error when enabling `-verbose` mode.

```
● snowflake-proxy.service - snowflake-proxy
     Loaded: loaded (/etc/systemd/system/snowflake-proxy.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2023-06-20 07:51:30 UTC; 21s ago
       Docs: man:snowflake-proxy
             https://snowflake.torproject.org/
   Main PID: 1625971 (proxy)
      Tasks: 5 (limit: 1146)
     Memory: 7.8M
        CPU: 88ms
     CGroup: /system.slice/snowflake-proxy.service
             └─1625971 /usr/bin/proxy -capacity 0 -verbose

Jun 20 07:51:30 bridge1 systemd[1]: Started snowflake-proxy.
Jun 20 07:51:30 bridge1 proxy[1625971]: 2023/06/20 07:51:30 snowflake-proxy 2.6.0
Jun 20 07:51:30 bridge1 proxy[1625971]: 2023/06/20 07:51:30 Proxy starting
Jun 20 07:51:30 bridge1 proxy[1625971]: 2023/06/20 07:51:30 Failed to prepare offer failed to create network: route ip+net: netlinkrib: address family not supported by protocol
Jun 20 07:51:30 bridge1 proxy[1625971]: 2023/06/20 07:51:30 error making WebRTC connection: failed to create network: route ip+net: netlinkrib: address family not supported by protocol
Jun 20 07:51:30 bridge1 proxy[1625971]: 2023/06/20 07:51:30 NAT type: unknown
```

Need to troubleshoot further when I have some time. I believe it has something to do with the systemd service possibly https://github.com/nvjacobo/snowflake/blob/main/templates/snowflake-proxy.service.j2#L22 ?

**Comment by xiaokangwang** [comment]
Looking into the code, the error line: "error making WebRTC connection: failed to create network: route ip+net: netlinkrib: address family not supported by protocol"

is generated by:
* https://github.com/pion/ice/blob/db5d7ea72b110ed3fbd1843b1a484ce91add933a/agent.go#L329
* https://github.com/pion/transport/blob/c8e9e563b5c52793a68e969499a91ee05e3ee246/stdnet/net.go#L41
* https://cs.opensource.google/go/go/+/refs/tags/go1.20.5:src/net/interface.go;l=105;drc=a2d2e6e7cb12c57cd8f5af64909882bab1dbca19
* https://cs.opensource.google/go/go/+/refs/tags/go1.20.5:src/net/interface_linux.go;l=17;drc=a2d2e6e7cb12c57cd8f5af64909882bab1dbca19

I think your theory is correct as, it suggests that this version of WebRTC's ICE requires NetlinkRIB system call to work, which might require it to be granted AF_NETLINK access in RestrictAddressFamilies.

**Comment by lunarthegrey** [comment]
Confirmed adding `AF_NETLINK` resolves the issue. Will submit a PR.

**Comment by nvjacobo** [comment]
thanks @lunarthegrey  @xiaokangwang!
