### ISSUE TITLE
get permissions via become solved problems for me

### ISSUE THREAD

**Issue by wolf128058** [nvjacobo/snowflake#5]
very nice work and very important to get some snowflake-proxies up atm. thank you!

i had to add some "become: yes" to tasks/ubuntu.yml to get that role running for me.
seems like it only runs if you are root.

**Comment by nvjacobo** [comment]
Hi @wolf128058!

I appreciate your words :) 

You are right. The role required to be deployed with root or sudo, in this case with become. 

I will add it on readme. 

Thanks

**Comment by nvjacobo** [comment]
Hi again @wolf128058 

For the moment I added info about it on 0bc9b22. 

Thank you for your comments. I will thinking about an approach or option that requirements less root privileges
