### ISSUE TITLE
Run it as snowflake user

### ISSUE THREAD

**Issue by kmille** [nvjacobo/snowflake#6]
Hey,
you create a snowflake user to build the proxy. Why do you run it as root? It seems to work as non-root user.  
I can create a PR and add some systemd hardening if you like.

**Comment by nvjacobo** [comment]
Hi @kmille! 

Thanks for your feedback. I think it's a good idea to switch to a non-root user :) 

Go ahead with your PR. Thank you very much! 

Jacobo
